### ISSUE TITLE
Unexpected error when just opening it.

### ISSUE THREAD

**Issue by xauuzd** [cashsignsesh/ProgrammingLanguageTutorialIdea#1]
I get this fatal error:
[!] FATAL: Expected 1 argument (path of file), with optional flags. Set argument to "help" to see flags. Got 0 args.

**Comment by jakefrey0** [comment]
Idk why I never saw this but basically you're supposed to do

"sunset ./path/to/sourcecode.sunset"
not just
"sunset"

because it's just a compiler and you need to feed it source code for it to compile something and you can edit that source code in anything, notepad, notepad++, emeditor (EmEditor syntax file can be found in the project)

**Comment by xauuzd** [comment]
I literally don't even remember what this is about LOL
2 years to reply is insane but fair enough
